export const labelConstants = {
  ABOUT_LBL: 'About',
  REGISTER_BTN: 'Register',
  LOG_IN_BTN: 'Log in',
  LOG_OUT_BTN: 'Log out',
  OK_BTN: 'Ok',
  HOME_LBL: 'Home',
  MY_TEAMS_LBL: 'Teams',
  MY_GAMES_LBL: 'Games',
  SETTINGS_LBL: 'Settings',
  START_GAME_LBL: 'Start new game',
  NEW_TEAM_LBL: 'Create new team',
  EDIT_ACCOUNT_LBL: 'Edit account',
  DELETE_ACCOUNT_LBL: 'Delete account',
  SAVE_BTN: 'Save',
  CANCEL_BTN: 'Cancel',
  CHANGE_PASSWORD_LBL: 'Change password',
  PLAYER_CATEGORIES: [{category: 'Men'}, {category: 'Women'}],
  PLAYER_POSITIONS: [{pos: 'Outside Hitter', val: 'OH'},
                      {pos: 'Setter', val: 'S'},
                      {pos: 'Middle Blocker', val: 'MB'},
                      {pos: 'Libero', val: 'L'},
                      {pos: 'Opposite', val: 'O'},
                      {pos: 'Any', val: 'ANY'}]
}
